INSERT INTO student VALUES('S001','Akash','Sharma',22,'Male',3,'Akash@123');
INSERT INTO student VALUES('S002','Samir','Sharma',21,'Male',3,'Samir@123');
INSERT INTO student VALUES('S003','Aman','Gupta',23,'Male',3,'Aman@123');

INSERT INTO country VALUES(1, 'USA');
INSERT INTO country VALUES(2, 'INDIA');
INSERT INTO state VALUES(1, 'TEXAS', 1);
INSERT INTO state VALUES(2, 'FLORIDA', 1);
INSERT INTO state VALUES(3, 'WEST BENGAL', 2);
INSERT INTO state VALUES(4, 'BIHAR', 2);
INSERT INTO city VALUES(1, 'AUSTIN', 1);
INSERT INTO city VALUES(2, 'TALLAHASSEE', 2);
INSERT INTO city VALUES(3, 'KOLKATA', 3);
INSERT INTO city VALUES(4, 'PATNA', 4);